ci: validar se os links do README são válidos
qa-brasil/qa-challenges pull request #2
Opened 2021-01-17 21:31 UTC by PauloGoncalvesBH

2021-01-17 22:07 UTC, brunopulis approved these changes

2021-01-17 22:09 UTC, brunopulis commented
@PauloGoncalvesBH você poderia verificar os conflitos que ocorreram?

2021-01-17 22:12 UTC, brunopulis requested changes
@PauloGoncalvesBH coloquei a lista em ordem alfabética e isso ocasionou um conflito, você poderia corrigir isso?

2021-01-17 22:21 UTC, PauloGoncalvesBH commented
@brunopulis conflito resolvido

2021-01-18 00:36 UTC, brunopulis approved these changes
LGTM 👍🏻

2021-01-18 00:36 UTC, merged